services:
  first-app:
    container_name: first-app
    restart: unless-stopped
    depends_on:
      - mongo
    build:
      context: ./..
      dockerfile: build/docker/Dockerfile
    environment:
      APP_NAME: firstapp
      APP_ENV: development
    networks:
      - app-network
    ports:
      - "8000:8000"
      - "50051:50051"

  second-app:
    container_name: second-app
    restart: unless-stopped
    build:
      context: ./..
      dockerfile: build/docker/Dockerfile
    environment:
      APP_NAME: secondapp
      APP_ENV: development
    networks:
      - app-network
#    ports:
#      - "8081:8081"

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data: