# Server configuration
server:
  grpc:
    port: ${GRPC_SERVER_PORT:50051}
    reflection: ${GRPC_SERVER_REFLECTION:true}
  http:
    host: ${HTTP_SERVER_HOST:}
    port: ${HTTP_SERVER_PORT:8000}

# Database configuration
database:
  uri: "mongodb://mongo:27017"