# App configuration
app:
  name: event-collector

# Server configuration
server:
  grpc:
    port: 50051
    reflection: true
  http:
    host: ""
    port: 8000

# Database configuration
database:
  uri: "mongodb://localhost:27017"