# App configuration
app:
  name: event-collector

# Log
logger:
  level: debug  # debug, info, warn, error, dpanic, panic, fatal
  encoding: json # json or console
  development: false
  outputPaths: stdout,logs/app_.log
  errorOutputPaths: stderr,logs/error.log
  disableCaller: true
  disableStacktrace: false
  sampling:
    initial: 100
    thereafter: 100

# Server configuration
server:
  grpc:
    port: 50051
    reflection: true
  http:
    host: ""
    port: 8000

# Database configuration
database:
  uri: "mongodb://localhost:27017"